http:
  middlewares:
    my-traefik-api-key-auth:
      plugin:
        traefik-api-key-auth:
          authenticationHeader: "true"
          authenticationheaderName: X-API-KEY
          keys:
            - 83AB3503-50AA-4B57-9386-B9F0BADF2013
            - 12345678-1234-5678-1234-567812345678
