# Traefik static configuration
entryPoints:
  web:
    address: ":80"

  traefik:
    address: ":8080"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    watch: true

  file:
    filename: "/etc/traefik/dynamic.yml"
    watch: true

api:
  dashboard: true
  insecure: true

experimental:
  plugins:
    traefik-api-key-auth:  # https://plugins.traefik.io/plugins/65f5043446079255c9ffd1ee/api-key-auth
      moduleName: "github.com/Septima/traefik-api-key-auth"
      version: "v0.2.3"
